### PR TITLE
Fix compilation failure

### PR DESCRIPTION
**Pull request by montjoie**
Hello this PR fix issues 1 and 2 and permit to check better needed libva version.

### CODE REVIEW

**Comment by montjoie** [comment]
By never tested I mean when running configure, you will never see "Checking for drm_fourcc.h".
Furthermore, if you get it from libdrm, it should be libdrm/drm_fourcc.h

By just removing the if;then around the drm_foucc.h detection, my gentoo didnt found it

**Comment by paulkocialkowski** [comment]
So what needs to be done here is to cleanup the check on libdrm.
Including from `libdrm/drm_fourcc.h` is  not correct: the libdrm include path must instead be added to `CFLAGS` (from pkg-config). Feel free to craft a fix in that direction, otherwise I will take a look at it at some point in the future.

**Comment by marcinkowskip** [comment]
@paulkocialkowski "while what we've been doing so far is to get it from libdrm" - if it's true how you compile this repository without undefined macro (DRM_FORMAT_MOD_ALLWINNER_MB32_TILED) error (from src/video.c file)? This macro is defined in the kernel headers, not in libdrm.

**Comment by montjoie** [comment]
The problem is that libdrm will never have the correct header until a long time.
Why not using kernel one which is easier to update (for the moment).

**Comment by ezequielgarcia** [comment]
I've no idea if this is the correct fix, but I am hitting the same issue, which I fix just hacking the `include` statement.

**Comment by paulkocialkowski** [comment]
That should no longer be required with the latest changes. Thanks!

**Pull request closed without merging**
